symfony_zero_api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /v1/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

symfonyzero_user:
    resource: "@ApiBundle/Resources/config/userRouting.yml"
    prefix:   /v1