parameters:
    symfonyzero.user.manager.class: ApiBundle\Manager\UserManager

services:
    symfonyzero.user.manager:
        class: %symfonyzero.user.manager.class%
        arguments: [@symfonyzero.user.repository ]